# Shell variables
# Generated by 'wal'
wallpaper="/home/admin/Documents/arch-papers/walls/hobbits-shire-final.png"

# Special
background='#0d0d0e'
foreground='#c2c2c2'
cursor='#c2c2c2'

# Colors
color0='#0d0d0e'
color1='#4E6E4C'
color2='#68695C'
color3='#8D6246'
color4='#688F67'
color5='#787A8B'
color6='#A2B5AF'
color7='#c2c2c2'
color8='#57576b'
color9='#4E6E4C'
color10='#68695C'
color11='#8D6246'
color12='#688F67'
color13='#787A8B'
color14='#A2B5AF'
color15='#c2c2c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
