--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/admin/Documents/arch-papers/walls/hobbits-shire-final.png"

-- Special
background="#0d0d0e"
foreground="#c2c2c2"
cursor="#c2c2c2"

-- Colors
color0="#0d0d0e"
color1="#4E6E4C"
color2="#68695C"
color3="#8D6246"
color4="#688F67"
color5="#787A8B"
color6="#A2B5AF"
color7="#c2c2c2"
color8="#57576b"
color9="#4E6E4C"
color10="#68695C"
color11="#8D6246"
color12="#688F67"
color13="#787A8B"
color14="#A2B5AF"
color15="#c2c2c2"
